import React from "react";
import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title></title>
      </head>
      <body>
        <nav>
            <Link href="/">
                Home
            </Link>
          <Link href={"/notes"}>
            Notes
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}